CREATE TABLE Account(
    ID INT PRIMARY KEY,
    CUST_NAME VARCHAR(255) UNIQUE,
    BALANCE INT NOT NULL DEFAULT 0
);

-- Add New Column
ALTER TABLE Account ADD INTEREST FLOAT NOT NULL DEFAULT 0;

-- Modify
ALTER TABLE Account MODIFY INTEREST DOUBLE NOT NULL DEFAULT 0;

DESC Account -- it will describe that table

-- Change Column - Rename The column
ALTER TABLE Account CHANGE COLUMN INTEREST SAVING_INTEREST FLOAT NOT NULL DEFAULT 0;

-- DROP Column
ALTER TABLE Account DROP COLUMN SAVING_INTEREST;

-- Rename the table
ALTER TABLE Account RENAME TO ACCOUNT_DETAILS;
